
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Lab3p1(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
 
wire [1:0] Y_wire;
    wire V_wire;

    P04to02(
        .SW(SW[3:0]),
        .Y(Y_wire),
        .V(V_wire),
        .LEDR(LEDR[2:0])
    );
 endmodule 
 
 



//=======================================================
//  Structural coding
//=======================================================
